services:
  fastapi-server:
    image: faith1712/fastapi-server
    build:
      context: ./backend
    environment:
      - INT_SERVER_PORT=${INT_SERVER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - INT_POSTGRES_PORT=${INT_POSTGRES_PORT}
      - INT_INFERENCE_PORT=${INT_INFERENCE_PORT}
    ports:
      - ${EXT_SERVER_PORT}:${INT_SERVER_PORT}
    restart: always
    # volumes:
    #   - ./backend:/app
    depends_on:
      db:
        condition: service_started
      inference_endpoint:
        condition: service_healthy
        restart: true

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - EXT_POSTGRES_PORT=${INT_POSTGRES_PORT}
    ports:
      - ${EXT_POSTGRES_PORT}:${INT_POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inference_endpoint:
    build:
      context: ./inference_endpoint
    ports:
      - ${EXT_INFERENCE_PORT}:${INT_INFERENCE_PORT}
    environment:
      - PORT=${INT_INFERENCE_PORT}
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: curl --fail http://inference_endpoint:${EXT_INFERENCE_PORT}/health || exit 1
      interval: 15s
      timeout: 2s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
